server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
    port: 6379
    host: 172.17.161.144
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 3
    timeout: 2000ms
  #这里是模拟集群的声明方式
  #    cluster:
  #      nodes: 172.17.161.144:6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_cache?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: 123456
    name: test_cache
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
    ehcache:
      config: classpath:ehcache.xml
riil:
  cache:
    namespace:
      - name: user1
        ttl: 200
      - name: user2
        ttl: 1000000